// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signin": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/app": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signin" | "/signup" | "/app";
  };
  "routes/layouts/backgroundPublicLayout.tsx": {
    id: "routes/layouts/backgroundPublicLayout";
    page: "/" | "/signin" | "/signup";
  };
  "routes/publicRoutes/landescape.tsx": {
    id: "routes/publicRoutes/landescape";
    page: "/";
  };
  "routes/publicRoutes/signin/signin.tsx": {
    id: "routes/publicRoutes/signin/signin";
    page: "/signin";
  };
  "routes/publicRoutes/signup/signup.tsx": {
    id: "routes/publicRoutes/signup/signup";
    page: "/signup";
  };
  "routes/layouts/backgroundSecureLayout.tsx": {
    id: "routes/layouts/backgroundSecureLayout";
    page: "/app";
  };
  "routes/secureRoutes/home/home.tsx": {
    id: "routes/secureRoutes/home/home";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layouts/backgroundPublicLayout": typeof import("./app/routes/layouts/backgroundPublicLayout.tsx");
  "routes/publicRoutes/landescape": typeof import("./app/routes/publicRoutes/landescape.tsx");
  "routes/publicRoutes/signin/signin": typeof import("./app/routes/publicRoutes/signin/signin.tsx");
  "routes/publicRoutes/signup/signup": typeof import("./app/routes/publicRoutes/signup/signup.tsx");
  "routes/layouts/backgroundSecureLayout": typeof import("./app/routes/layouts/backgroundSecureLayout.tsx");
  "routes/secureRoutes/home/home": typeof import("./app/routes/secureRoutes/home/home.tsx");
};